// Generated by https://quicktype.io

export interface OrderModel {
  id: number
  code: string
  shop: string
  customer_name: string
  customer_phone: string
  customer_address: string
  customer_note: string
  total_price: string
  shipping_price: string
  cod_price: string
  cod_edit_price: string
  delivered_at: null
  devivering_at: null
  note: null
  user_id: null
  agent_id: null
  agent_share_id: null
  shipper_id: null
  status: number
  created_at: string
  updated_at: string
}
